/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类: 
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "he/him": "他",
    "she/her": "她",
    "Hard reset": "硬重置",
    "Event log": "事件日志",
    "Basic egg": "基础蛋",
    "Roll!": "投掷!",
    "Send away": "放生",
    "Emerald dragon": "翡翠龙",
    "Blue dragon": "蓝龙",
    "Silver dragon": "银龙",
    "Gold dragon": "金龙",
    "Ruby dragon": "红宝石龙",
    "Green dragon": "绿龙",
    "Yellow dragon": "黄龙",
    "Orange dragon": "橙龙",
    "Purple dragon": "紫龙",
    "Tips": "提示",
    "Tip 0: This is a tip test!": "提示 0: 这是一个提示测试！",
    "Tip 1: The three basic dragons can spawn randomly at any time. Other dragons have to be attained through other methods!": "提示 1: 三条基本的龙可以在任何时候随机生成。其他龙必须通过其他方法获得！",
    "Tip 2: Click a dragon to see more information about it!": "提示 2: 点击龙查看更多信息！",
    "Tip 3: Dragons occasionally get green bonus score icons (up to 3 on screen at once)! These give free score based on that dragon's production. Also, a SUPER bonus score icon may appear rarely.": "提示 3: 龙偶尔会得到绿色的奖励分数图标（最多3个在屏幕上一次）！这些都是基于龙的生产免费得分。此外，超级奖励分数图标可能很少出现。",
    "Tip 4: Breeding allows you to unlock dragons that can't otherwise be obtained. Get creative! Dragons can also breed with the same gender. Love wins": "提示 4: 繁殖可以让你解锁其他方式无法获得的龙。很有创意!龙也可以与同性繁殖。爱胜过一切",
    "Original dragon sprite by Zaxolotl": "龙图片由Zaxolotl原创",
    "Basic dragon": "基础龙",
    "A wild Basic dragon [Green] appeared!": "一只野生的基本龙（绿色）出现了！",
    "Additional work by acod": "额外的工作由acod",
    "Breeding": "繁殖",
    "Click a dragon to see info!": "点击一条龙查看信息！",
    "Created by Demonin": "由Demonin创造",
    "Daily roll": "每日投掷",
    "Decorations": "装饰品",
    "Gunk:": "粘稠物: ",
    "Manage dragons": "管理龙",
    "Manage your dragons!": "管理你的龙！",
    "No dragon selected...": "没有龙被选中…",
    "Rarities:": "稀有度: ",
    "Remove all decorations": "移除所有装饰",
    "Remove decoration": "移除装饰",
    "Reset selections": "重置选择",
    "Select a dragon to breed!": "选择一条龙来繁殖！",
    "Skip incubation": "跳过孵化",
    "Spawn wild dragons": "生成野生龙",
    "Test text!": "测试文本！",
    "test text 2": "测试文本2",
    "You hatched a Blue dragon!": "你孵出了一条蓝龙！",
    "You hatched a Yellow dragon!": "你孵出了一条黄龙！",
    "they/them": "他们",
    "Breeding probabilities:": "繁殖概率:",
    "Incubating Basic dragon": "孵化基础龙",
    "Select some dragons to see their probabilities!": "选择一些龙，看看他们的繁殖概率！",
    "Bathtub": "浴缸",
    "Chair": "椅子",
    "Computer": "电脑",
    "Decoration crate": "装饰箱",
    "Fridge": "冰箱",
    "Gemstone": "宝石",
    "Glowing egg": "发光的蛋",
    "Large mace": "大狼牙棒",
    "Large sword": "大剑",
    "Lightning dragon": "闪电龙",
    "Pile of coins": "一堆硬币",
    "Pleasant gradient dragon": "愉快的渐变龙",
    "Power egg": "力量蛋",
    "Rug": "地毯",
    "score": "分数",
    "Short plant": "矮株植物",
    "Tall plant": "高大植物",
    "Toilet": "厕所",
    "You won a Mr. Gunky!": "你获得了 甘奇先生!",
    "You won a Rug!": "你获得了 地毯!",
    "You won a Goat!": "你获得了 山羊!",
    "You won a Large mace!": "你获得了 大狼牙棒!",
    "You won a Large sword!": "你获得了 大剑!",
    "Incubating Pleasant gradient dragon": "孵化愉快的渐变龙",
    "You unboxed a Bathtub!": "你从箱子中取出一个浴缸!",
    "You won a Rug from your daily roll!": "你从你的日常投掷中赢得了 地毯！",
    "You won a Goat from your daily roll!": "你从你的日常投掷中赢得了 山羊！",
    "You won a Mr. Gunky from your daily roll!": "你从你的日常投掷中赢得了 甘奇先生！",
    "You won a Large mace from your daily roll!": "你从你的日常投掷中赢得了 大狼牙棒！",
    "You won a Large sword from your daily roll!": "你从你的每日投掷中赢得了 大剑！",
    "Your Basic dragon [Purple] has hatched!": "你的基本龙[紫色]已经孵化了！",
    "Your Pleasant gradient dragon has hatched!": "你的愉快的渐变龙已经孵化了！",
    "Gemstone egg": "宝石蛋",
    "Goat": "山羊",
    "Mr. Gunky": "甘奇先生",
    "Incubating Goat": "孵化山羊",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "You hatched a Lightning dragon!": "你孵化了一条 闪电龙！",
    "You hatched a Silver dragon!": "你孵化了一条 银龙！",
    "You hatched a Pleasant gradient dragon!": "你孵化了一条 愉快的渐变龙！",
    "Power egg will unlock at 1,000,000 score!": "力量蛋将解锁于 1,000,000 分数!",
    "Gemstone egg will unlock at 5,000,000 score!": "宝石蛋将解锁于 5,000,000 分数！",
    "Daily roll and decorations will unlock at 500,000 score!": "每日投掷和装饰品将解锁于 500,000 分数！",
    "Glowing egg will unlock at 250,000 score!": "发光蛋将解锁于 250,000 分数！",
    "Breeding will unlock at 100,000 score!": "繁殖将解锁于 100,000 分数！",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如: Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头: "Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑: ",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式: ",
    "In-line Exponent: ": "直列指数: ",
    "Single-Tab Mode: ": "单标签模式: ",
    "Time Played: ": "已玩时长: ",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示: ",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "???: ": "???: ",
    "Large sword: ": "大剑: ",
    "Lightning dragon: ": "闪电龙: ",
    "Large mace: ": "大狼牙棒: ",
    "Gemstone: ": "宝石: ",
    "Computer: ": "电脑: ",
    "Fridge: ": "冰箱: ",
    "Goat: ": "山羊: ",
    "Chair: ": "椅子: ",
    "Bathtub: ": "浴缸: ",
    "Pile of coins: ": "一堆硬币: ",
    "Pleasant gradient dragon: ": "愉快的渐变龙: ",
    "Dragons: ": "龙: ",
    "Short plant: ": "矮株植物: ",
    "Tall plant: ": "高大植物: ",
    "Rug: ": "地毯: ",
    "Toilet: ": "厕所: ",
    "Score/second: ": "分数/秒: ",
    "score/second: ": "分数/秒: ",
    "Time left: ": "剩余时间: ",
    "Ruby dragon: ": "红宝石龙: ",
    "Gold dragon: ": "金龙: ",
    "Blue dragon: ": "蓝龙: ",
    "Silver dragon: ": "银龙: ",
    "Emerald dragon: ": "翡翠龙: ",
    "Green dragon: ": "绿龙: ",
    "Yellow dragon: ": "黄龙: ",
    "Bestiary ID: ": "图鉴 ID: ",
    "Dodeca Park v": "十二龙公园 v",
    "Basic dragon [Green]: ": "基础龙 [绿色]: ",
    "Basic dragon [Orange]: ": "基础龙 [橙色]: ",
    "Basic dragon [Purple]: ": "基础龙 [紫色]: ",
    "Time until more rolls: ": "获得下次投掷机会还剩: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如: 13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾: " Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " [Green]": " [绿色]",
    " [Orange]": " [橙色]",
    " [Purple]": " [紫色]",
    "Bestiary": "图鉴",
    "Breed!": "繁殖！",
    "Save": "保存",
    "Import": "导入",
    " (from basic egg)": " (来自基础蛋)",
    " (from glowing egg)": " (来自发光蛋)",
    " (from gemstone egg)": " (来自宝石蛋)",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^你放生(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字: (\d+)
//字母加数字: ([\d\.]+[A-Za-z])
//逗号: ([\d\.,]+)
//小数点: ([\d\.]+)
//原样输出的字段: (.+)
//换行加空格: \n(.+)
//&nbsp;空格: \xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Produces (.+) score\/second$/, '产出 $1 分数/秒'],
    [/^Producing (.+) score\/second$/, '产出 $1 分数/秒'],
    [/^Producing (.+) gunk\/second$/, '产出 $1 粘稠物/秒'],
    [/^You gained (.+) super bonus score!$/, '你获得了 $1 超级奖励分数！'],
    [/^You won (.+) score!$/, '你获得了 $1 分数！'],
    [/^You gained (.+) bonus score!$/, '你获得了 $1 奖励分数！'],
    [/^You have (.+) rolls left$/, '你还剩余 $1 投掷'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You own (.+) of this decoration$/, '已拥有 $1 个该饰品'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1 小时 $2 分'],
    [/^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/, '$1 小时 $2 分 $3 秒'],
    [/^([\d\.]+)h ([\d\.]+)s$/, '$1 小时 $2 秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Dragon ([\d\.,]+)$/, '龙 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本: $1 点数'],
    [/^Req: (.+) elves$/, '要求: $1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求: $1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途: $1\/'],
    [/^workers: (\d+)\/$/, '工人: $1\/'],

]);